# Generated by Django 4.2.1 on 2023-05-04 08:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("workouts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "leg_exercise",
                    models.CharField(
                        choices=[
                            ("Squat", "Squat"),
                            ("Deadlift", "Deadlift"),
                            ("Leg Press", "Leg Press"),
                            ("Calf Raises", "Calf Raises"),
                            ("Leg Extension", "Leg Extension"),
                            ("Lying Leg Curl", "Lying Leg Curl"),
                        ],
                        max_length=200,
                    ),
                ),
                (
                    "push_exercise",
                    models.CharField(
                        choices=[
                            ("Bench Press", "Bench Press"),
                            ("Overhead Press", "Overhead Press"),
                            ("Chest Cable Fly", "Chest Cable Fly"),
                            ("Tricep Extension", "Tricep Extension"),
                            ("Lateral Raises", "Lateral Raises"),
                        ],
                        max_length=200,
                    ),
                ),
                (
                    "pull_exercise",
                    models.CharField(
                        choices=[
                            ("Lat Pulldown", "Lat Pulldown"),
                            ("Bent-Over Row", "Bent-Over Row"),
                            ("Seated Cable Row", "Seated Cable Row"),
                            ("DB Shrugs", "DB Shrugs"),
                            ("Barbell Curls", "Barbell Curls"),
                            ("Reverse Curls", "Reverse Curls"),
                        ],
                        max_length=200,
                    ),
                ),
                (
                    "sets",
                    models.PositiveIntegerField(
                        choices=[(2, 2), (3, 3), (4, 4), (5, 5), (6, 6)]
                    ),
                ),
                (
                    "reps",
                    models.PositiveIntegerField(
                        choices=[(5, 5), (8, 8), (10, 10), (12, 12), (15, 15), (20, 20)]
                    ),
                ),
                ("weight", models.DecimalField(decimal_places=2, max_digits=5)),
                ("is_completed", models.BooleanField(default=False)),
                (
                    "assignee",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercises",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercises",
                        to="workouts.workout",
                    ),
                ),
            ],
        ),
    ]
