# Generated by Django 4.2.1 on 2023-05-04 08:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("exercises", "0002_remove_exercise_pull_exercise_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="exercise",
            old_name="leg_exercise",
            new_name="exercise_type",
        ),
    ]
