# Generated by Django 4.2.1 on 2023-05-04 08:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("exercises", "0004_alter_exercise_weight"),
    ]

    operations = [
        migrations.RenameField(
            model_name="exercise",
            old_name="is_completed",
            new_name="completed",
        ),
    ]
