# Generated by Django 4.2.1 on 2023-05-04 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("workouts", "0001_initial"),
        ("exercises", "0005_rename_is_completed_exercise_completed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="workout",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exercises",
                to="workouts.workout",
            ),
        ),
    ]
